//! Build metadata generated by `build.rs`.

/// Short git commit SHA of the build, shown in the home page footer.
/// Falls back to `"unknown"` outside a git checkout.
pub const BUILD_GIT_COMMIT_SHA: &str = env!("BANGS_BUILD_GIT_COMMIT_SHA");
