name: Publish Application on GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Rust/WASM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2

    - name: Install wasm-bindgen CLI
      run: make install-bindgen

    - name: Compile and test
      run: make test

    - name: Browser tests
      run: |
        if [ -d "$CHROMEWEBDRIVER" ]; then
          export CHROMEDRIVER="$CHROMEWEBDRIVER/chromedriver"
        fi
        make test-wasm

    - name: Build distribution
      run: make dist

    - name: Fix permissions
      run: |
        chmod -v -R +rX "dist/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Deploy to GitHub Pages
      run: |
        ./.github/scripts/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
