name: Publish Application on GitHub Pages
on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build Kotlin/JS
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile and Test
      run: ./gradlew check

    - name: Build distribution
      run: ./gradlew jsBrowserDistribution

    - name: Fix permissions
      run: |
        chmod -v -R +rX "build/dist/js/productionExecutable/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Deploy to GitHub Pages
      run: |
        ./.github/scripts/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
